import {
  CARD_EDITOR_FORM_INIT,
  CARD_TEMPLATE_TYPE,
  DESC_EDITOR_FORM_INIT,
  DESC_TEMPLATE_TYPE,
  MAIN_EDITOR_FORM_INIT,
  MAIN_TEMPLATE_TYPE
} from "~/components";

export const TEMPLATE_INIT_MAP = {
  [MAIN_TEMPLATE_TYPE]: MAIN_EDITOR_FORM_INIT,
  [DESC_TEMPLATE_TYPE]: DESC_EDITOR_FORM_INIT,
  [CARD_TEMPLATE_TYPE]: CARD_EDITOR_FORM_INIT
} as const;
