import {
  DESC_TEMPLATE_INIT,
  DESC_TEMPLATE_TYPE,
  MAIN_TEMPLATE_INIT,
  MAIN_TEMPLATE_TYPE
} from "~/components";

export const TEMPLATE_INIT_MAP = {
  [MAIN_TEMPLATE_TYPE]: MAIN_TEMPLATE_INIT,
  [DESC_TEMPLATE_TYPE]: DESC_TEMPLATE_INIT
} as const;
